source 'https://rubygems.org'

gem 'dotenv', '2.2.1'
gem 'omniauth', '~> 1.4.2'
gem 'omniauth-vimeo', '~> 2.0.1'
gem 'pry-remote'
gem 'redis', '3.3.3'
gem 'redis-namespace', '1.5.3'
gem 'sidekiq', '5.0.0'
gem 'sidekiq-unique-jobs', '~> 5.0.8'
gem 'sinatra', '2.0.0'
gem 'vhx-ruby', '0.0.9'
gem 'vimeo_me2', git: 'https://github.com/jamiew/vimeo_me2/'
